### ISSUE TITLE
TQREAL + pc2pe codes not working with SK5

### ISSUE THREAD

**Issue by pdeperio** [pdeperio/SKana#6]
Attempting to run [tqreal.F](https://github.com/pdeperio/SKana/blob/master/tqreal/tqreal.F) followed by [llaser_qb_c.cc](https://github.com/pdeperio/SKana/blob/master/pc2pe/llaser_qb_c.cc) (based on [sample_snld.cc](https://github.com/pdeperio/SKana/blob/master/skroot/sample_snld.cc) from @seanxia8) on **pc2pe** SK5 laser data (runs 80871, 80873, 80875), but it seems to miss the laser timing peak in the following plot:

![ttof_sk4_vs_sk5](https://user-images.githubusercontent.com/8642192/54943838-63cc6280-4eef-11e9-8dff-120d2cbd75b2.png)

where it works fine for SK4 (runs 61892-61895). Is there anything that needs to change to apply these programs to SK5? (Note, I already tried using a [table_version.99.00](https://github.com/pdeperio/SKana/blob/master/tqreal/table_version.99.00) I found in @seanxia8's ```tqreal``` directory, [here](https://github.com/pdeperio/SKana/blob/master/tqreal/tqreal.F#L44), but it just seems to shift the timing distribution negative.)

One hint from from Hide-san's code below seems to show some manual timing gate shift; is this necessary in tqreal.F?
```fortran
c      /disk02/usr6/thide/TQ_map_2019/20190325_relative_pc2pe/calib/selcalib.F:289

         do ihitz=1,NQISKZ
           if (iand(ihtiflz(ihitz), 2).ne.0) then ! *** in gate ***
            if(icabiz(ihitz).eq.15001) then
               if(iflag_15001.eq.0) then
                  IT1 = itiskz(ihitz)
               else if(iflag_15001.eq.1) then
                  IT2 = itiskz(ihitz)
               endif
               iflag_15001 = iflag_15001 + 1
            endif

            if(icabiz(ihitz).eq.15012) iflag_laser = 1 ! laser

         enddo

         if(iflag_15001.eq.2 .and. IT1.eq.0) then

c*** shift timing gate manually
            if(iflag_laser.eq.1) then
               IDIF = IT2 - IT1
            else
               IDIF = IT2 - IT1 - 2050
            endif
            call set_timing_gate(it0sk + IDIF)
            CALL SKREAD(-10,*1002,*1001,*10,*10)
            call delete_outside_hits()
         endif
```
---------------------------------
There are README instructions in the parent directories [here](https://github.com/pdeperio/SKana/tree/master/tqreal) and [here](https://github.com/pdeperio/SKana/tree/master/pc2pe) in case you have a chance to reproduce.

**Comment by seanxia8** [comment]
Hey Patrick,

That manual timing gate shift might be the result of TQ map calibration.
And that may be the reason why this time the tqreal doesn't work for SK5 because we don't have such a constant yet.
Have you tried to comment out that 2050 gate shift and see what will happen? Since you are using table_v99, which means no timing correction is applied.

**Comment by pdeperio** [comment]
Ah sorry for confusion, I'm not actually using Hide-san's code. He just said his is working, and that was just one hint I noticed.

**Comment by seanxia8** [comment]
It looks like the SK5 data has extremely low stats compared to the SK4?
There is actually a small peak in ttof for SK5, but it's so small that becomes invisible in the log scale.

For example, if just comparing run61889 and run80871's ttof, the relative peak hight: (max-background) is 3 orders of magnitude different. (run61889: ~10^5 and run80871: ~500).
![image](https://user-images.githubusercontent.com/47470101/54976343-67d6ae00-4fdd-11e9-9242-c38a9e186b50.png)
![image](https://user-images.githubusercontent.com/47470101/54976347-6b6a3500-4fdd-11e9-86fb-4bd64f93ff54.png)

It might suggest that the timing of SK5 data is more broadened channel by channel. This may be more likely caused by the constants, i.e. the timing correction factor at each channel. 

It seems like only an overall constant is applied? I'm wondering if there's such a timing correction constant stored somewhere in one of the const tables.

**Comment by pdeperio** [comment]
I noticed that too, but it looks like that small bump is also present in SK4 data if you zoom in too (not sure what it's from):

![ttof_sk4_vs_sk5_zoom](https://user-images.githubusercontent.com/8642192/55014595-7c4c8380-4fa8-11e9-90e0-117e66244dab.png)

so it seems like the code is missing the laser hits completely in SK5.

**Comment by seanxia8** [comment]
Ah yes that's true.
The small bump might just be an afterpulse or something.
Do you know which light source it is? (Nickel, TQ, or Xenon)?
It seems like it's assuming Nickel in the tqreal by enabling trigger in channel 15012.
But it would be different for the other sources, i.e. TQ at 15009. Not sure about Xenon, but it might be the same one for autocalib?

**Comment by pdeperio** [comment]
It's the LSI (autocalib/TQ?) laser. Moriyama-san and Hide-san checked that it's triggering channel 15012.

**Comment by seanxia8** [comment]
Ah okay.
Sorry for the long break...I was having some trouble with the internet at the t2k meeting.
Do you if the autocalib has been stopped during the daq of this pc2pe?
Cuz according to Tanaka-san's code, it seems like if the autocalib is on (ch 15001), it's gonna cause that 2050 shift.
I guess that's to avoid overlapping the triggers?

**Comment by seanxia8** [comment]
I just noticed that the charge of hits is quite low for SK5 data (~1pe on average).
But for SK4 it was fairly big.
Were we taking the low intensity data for those runs? If that's the case then I think missing a peak in t-tof is quite reasonable?

**Comment by pdeperio** [comment]
Thanks a lot for helping, Junjie. Sorry, I've also been busy with other things the past few days.

I'm not sure, but I guess autocalib is off during "test" run?

There are two intensities for pc2pe data taking. Please see [this spreadsheet](https://docs.google.com/spreadsheets/d/1k3jO6WDPLnsYxZszKDaTvJiOfG688_lleVT4MxfVDJc/edit?usp=sharing) for the datasets and [these slides](https://docs.google.com/presentation/d/114YEnVFuktB09lttl7OcSfyz_-iaSJvlCXZQrk-cKv8/edit#slide=id.g550e87eea3_0_131) for my first study of SK4, where the low intensity seems to also work as expected (p.5).

**Comment by seanxia8** [comment]
Not at all. I didn't have a chance to say thanks for taking this job, which was originally assigned to Nishimura-san (and therefore me).

The autocalib is a cronjob that has to been switched on/off manually. Running in "test" mode doesn't stop the autocalib by itself. We may need to confirm with who's taking the data that the autocalib has been manually turned off?

Yeah I've seen those plots. It's so strange then why it doesn't work this time. I've tried to use another library to compile (the sklowe lib and atmpd_18a because these are what I use for tq) but it doesn't change the results...It seems like the problem is more upstream in tqreal or even before that? I cannot see anything wrong in the llaser_qb_c.cc...

**Comment by pdeperio** [comment]
Fixed by Koshio-san's new ```tqreal/tqreal_ls_sk5.F``` (https://github.com/pdeperio/SKana/commit/dc3e6b471b66f7519562595ab5c15bf675c71424)
